web/docker_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_page.urls')),
    path('', include('system_check.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/home_page/urls.py
from django.urls import path
from . import views

app_name = 'home_page'
urlpatterns = [
    path('', views.index, name='index'),
]

web/system_check/urls.py
from django.urls import path
from .views import health_check

urlpatterns = [
    path('health/', health_check, name='health-check'),
]

web/home_page/models.py
from django.db import models

default_message = (
    "Hello Jeremy,"
    "\n\nI'd like to schedule an interview with you...\n\n"
)

# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(blank=False, null=False)
    last_name = models.CharField(blank=False, null=False)
    phone_number = models.CharField(blank=True, null=True)
    email = models.EmailField(blank=False, null=False)
    comments = models.TextField(blank=False, null=False, default=default_message)

web/system_check/models.py
from django.db import models

# Create your models here.

web/home_page/forms.py
from .models import *
from django import forms
from django.forms import ModelForm, TextInput, EmailInput, Textarea


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        widgets = {
            'first_name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'First Name...',
            }),
                'last_name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Last Name',
            }),
                'phone_number': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Phone Number...',
            }),
            'email': EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Email...',
            }),
            'comments': Textarea(attrs={
                'class': 'form-control',
            }),
        }

web/home_page/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .forms import *
from .models import *
from pathlib import Path
from django.conf import settings
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

# Create your views here.
def index(request):
    context = {}
    context['form_submitted'] = False

    # About Section cards
    context['about_cards'] = []
    about_cards = [
        {
        'header': 'Goals',
        'text': (
            "<p>I am seeking a career as a full-stack software engineer; "
            "however, I am also open to a career focused on the back-end. "
            "The focus of my studies has been a Python-based stack; however, "
            "I am open to and enjoy learning new languages. I am especially "
            "interested in learning more C/C++.</p>"
        )
        },
        {
            'header': 'Work Experience',
            'text': (
                "<ul><li>2 years - Teaching English as a second language</li>"
                "<li>5 years - Helped start and run a tourism business</li>"
                "<li>5 years - Firefighter/EMT</li>"
                "<li>4 months - Technical Services Analyst (SQL)</li></ul>"
            )
        },
        {
            'header': 'Education',
            'text': (
                "<ul><li>B.A International Studies</li>"
                "<li>Software Developer Using Python - Community College "
                "non-degree career course</li>"
                "<li>Certiport IT Specialist in Python</li>"
                "<li>Certifport IT specialist in Databases</li>"
                "<li>1 1/2 years programming full-time self-study</li>"
            )
        }
    ]
    for about in about_cards:
        name = about['header'].lower().replace(' ', '-')
        context['about_cards'].append({
            'header': about['header'],
            'text': about['text'],
            'card_id': name,
            'parent_id': f'{name}-card',
            'front_id': f'{name}-front',
            'back_id': f'{name}-back',
        })

    # Skills section cards
    context['skills'] = []
    skills = [
        'Front End',
        'Back End',
        'Web Based',
        'Misc',
    ]
    for skill in skills:
        name = skill.lower().replace(' ', '-')
        temp_dict = {
            'header': skill,
            'card_id': name,
            'front_id': f'{name}-front',
            'back_id': f'{name}-back',
        }
        logos_path = Path.joinpath(Path(settings.BASE_DIR, 'static', 'logos', f'{skill.lower().replace(' ', '_')}'))
        logos = [name for name in os.listdir(logos_path) if name.endswith('.png')]
        temp_dict['logos'] = [f"static/logos/{skill.lower().replace(' ', '_')}/{logo}" for logo in logos]
        context['skills'].append(temp_dict)
    
    # Project section cards
    context['projects'] = [
        {
        'name': 'Portfolio',
        'img_url': 'site_pictures/portfolio_screenshot.png',
        'text': (
            "This project was created using Python's Django "
            "framework and PostgreSQL in Docker containers. "
            "It is running on an Ubuntu server using Nginx."
        ),
        'github_link': 'https://github.com/packardjc2024/docker_portfolio',
        'project_link': "#",
        'alt': 'Portofolio Screenshot',
        },
        {
        'name': "Docker Setup",
        'img_url': 'site_pictures/docker_setup_screenshot.png',
        'text': (
            "This app automates setting up a new Django/Postgres "
            "dockerized app. All you have to do is enter in the secrets "
            "necessary for the app and the app will encrypt the secrets, "
            "create the Django, Postgres database, and docker files all "
            "for you. Spinning up a new dockerized app only takes seconds!"
        ),
        'github_link': 'https://github.com/packardjc2024/docker_setup',
        'project_link': False,
        'alt': 'Docker Setup Screenshot',
        },
        {
        'name': "CSVQL",
        'img_url': '/site_pictures/csvql.png',
        'text': (
            "Coming Soon..."
        ),
        'github_link': '',
        'project_link': '',
        'alt': 'CSVQL Screenshot',
        },
    ]

    # Handle requestes and serve html files
    if request.method == 'GET':
        context['contact_form'] = ContactForm()
    elif request.method == 'POST':
        load_dotenv()
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            # Process the form
            data = contact_form.cleaned_data
            contact_form.save()
            # Send an email
            sender = settings.EMAIL_HOST_USER
            recipient = settings.EMAIL_HOST_USER
            host = settings.EMAIL_HOST
            port = settings.EMAIL_PORT
            password = settings.EMAIL_HOST_PASSWORD
            server = smtplib.SMTP(host, port)
            server.starttls()
            server.login(sender, password)
            message = MIMEMultipart()
            message['From'] = sender
            message['To'] = recipient
            message['Subject'] = 'Contact Form Submitted'
            body = (
                f'From: {data['first_name']} {data['last_name']}\n'
                f'Email: {data['email']}\n'
                f'Phone Number: {data['phone_number']}\n\n'
                f'Comments: {data['comments']}'
            )
            message.attach(MIMEText(body, 'plain'))
            server.sendmail(sender, recipient, message.as_string())
            server.quit()
            context['form_submitted'] = True
        else:
            context['context_form'] = contact_form
    return render(request, 'home_page/index.html', context)

web/system_check/views.py
from django.http import HttpResponse

# Create your views here.
def health_check(request):
    return HttpResponse("OK", status=200)

web/home_page/templates/home_page/index.html
{% extends 'base.html' %}
{% load static %}


<!-- Add the static files to the header block -->
{% block header_extension %}
<link rel="stylesheet" type="text/css" href='{% static "home_page/home_page.css" %}'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'home_page/home_page.js' %}"></script>
{% endblock %}


<!-- Add the index's content to the main header block -->
{% block body_extension %}

<!-- Welcome Section -->
<div class="welcome-background" id="welcome-section"> 

    <!-- Welcome container with typewriter effect -->
    <div class="welcome-container" id="welcome-container">
        <h1 id="hello-container" class="caret-container"></h1>
        <h1 id="name-container" class=""></h1>
    </div>

</div>

<!-- About Section -->
<div class="section" id="about-section">

    <h1 class="section-header">About Jeremy</h1>
    <div class="about-container">
        <!-- Head shot Card -->
        <div class="about-card-parent" id="about-head-shot-card">
            <img alt="Head Shot" class="head-shot-img" src="{% static 'site_pictures/head_shot.png' %}">
        </div>
        <!-- About Card Template -->
         {% for about in about_cards %}
        <div class="about-card-parent" id="{{ about.parent_id }}">
            <div class="flip-parent">
                <div class="flip-container">
                    <div class="flip-card about-flip-card" id="{{ about.card_id }}">
                        <div class="flip-front about-flip-front glass-container" id="{{ about.front_id }}">
                            <h2>{{ about.header }}</h2>
                        </div>
                        <div class="flip-back about-flip-back glass-container" id="{{ about.back_id }}">
                            {{ about.text|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

<!-- Skills Section -->
<div class="section" id="skills-section">

    <h1 class="section-header">Python Full-Stack Developer Skills</h1>
    <div class="skills-container">
        <!-- Skills card template -->
         {% for skill in skills %}
        <div class="skills-card-parent">
            <div class="flip-parent">
                <div class="flip-container">
                    <div class="flip-card skills-flip-card" id="{{ skill.card_id }}">
                        <div class="flip-front skills-flip-front glass-container" id="{{ skill.front_id }}">
                            <h2>{{ skill.header }}</h2>
                        </div>
                        <div class="flip-back skills-flip-back logos-container glass-container" id="{{ skill.back_id }}">
                            {% for logo in skill.logos %}
                            <img src="{{ logo }}" class="moving-logo">
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

<!-- Projects Section -->
<div class="section" id="projects-section">

    <h1 class="section-header">Projects</h1>
    <div class="project-cards-container">
        {% for project in projects %}
        <div class="glass-container project-col">
            <div class="project-row">
                <h6>{{ project.name }}</h6>
            </div>
            <div class="project-row">
                <img class="project-img" src="{% static project.img_url %}" alt="{{ project.alt }}">
            </div>
            <div class="project-row">
                <p class="w-100 project-text text-center">
                    {{ project.text }}
                </p>
            </div>
            <div class="project-row justify-content-around">
                {% if project.project_link %}
                <a class="button" href="{{ project.github_link}}">GitHub</a>
                <a class="button" href="{{ project.project_link }}">Project</a>
                {% else %}
                <a class="button" href="{{ project.github_link}}">GitHub</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>

</div>

<!-- Contact Section -->
<div class="section" id="contact-section">

    <h1 class="section-header">Let's Talk</h1>
    <div class="contact-container">
        <div class="form-container glass-container">
            {% if not form_submitted %}
            <form method="POST" action="{% url 'home_page:index' %}" id="contact-form">
                {% csrf_token %}
                {{ contact_form }}
                <div class="w-100 d-flex justify-content-center align-items-center m-2">
                    <button class="btn btn-primary" type="submit">Submit</button>
                </div>
            </form>
            {% else %}
            <h6>Thank you for your interest. I will get in touch with you shortly!</h6>
            {% endif %}
        </div>
    </div>

</div> 

{% endblock %}

web/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Programming on Demand</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/android-chrome-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/android-chrome-512x512.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon.ico' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <!-- Bootstrap and JQuery-->
    <script type="text/javascript" src="{% static 'jquery.js' %}"></script>
    <script type="text/javascript" href="{% static 'bootstrap.bundle.min.js' %}"></script>
    <link rel="stylesheet" type=text/css href="{% static 'bootstrap.min.css' %}">
    <!-- Project level CSS and JS Files -->
    <link rel="stylesheet" type="text/css" href='{% static "project.css" %}'>
    <script type="text/javascript" src="{% static 'project.js' %}"></script>
    <!-- Block for Apps to add CSS and JS Files -->
    {% block header_extension %}
    {% endblock %}
    
</head>

<body>

    <header class="fixed-top" id="header">
        <div class="top-navbar navbar-background" id="top-navbar">
            <div class="top-navbar-left-side">
                <a class="img-link" href="{% url 'home_page:index' %}">
                    <img id="pod-img" src="{% static 'site_pictures/pod_logo.png' %}" alt="Programming on Demand Logo">
                </a>
                <a class="header-text section-link" href="#welcome-section">Portfolio</a>
            </div>
            <!-- Medium screen and up navbar -->
            <div class="top-navbar-right-side-large" id="normal-navbar">
                <a class="header-text section-link" href="#about-section">About</a>
                <a class="header-text section-link" href="#skills-section">Skills</a>
                <a class="header-text section-link" href="#projects-section">Projects</a>
                <a class="header-text section-link" href="#contact-section">Contact</a>
            </div>
            <!-- Small screen navbar -->
            <div class="top-navbar-right-side-small dropdown-parent" id="dropdown-navbar">
                <img src="{% static 'site_pictures/menu.svg' %}" height="30px" id="menu-button">
                <div class="dropdown-container" id="dropdown-container">
                    <a class="header-text section-link" href="#about-section">About</a>
                    <a class="header-text section-link" href="#skills-section">Skills</a>
                    <a class="header-text section-link" href="#projects-section">Projects</a>
                    <a class="header-text section-link" href="#contact-section">Contact</a>
                </div>
            </div>
        </div>
    </header>

    <main>
        {% block body_extension %}
        {% endblock %}
    </main>

    <footer>
        <div class="bottom-navbar">
            <p id="copyright">&copy; Programming On Demand 2025</p>
        </div>
    </footer>

</body>

</html>